export const GET_ELECTRONICS_DATA_REQUEST = "GET_ELECTRONICS_DATA_REQUEST";
export const GET_ELECTRONICS_DATA_SUCCESS = "GET_ELECTRONICS_DATA_SUCCESS";
export const GET_ELECTRONICS_DATA_FAILURE = "GET_ELECTRONICS_DATA_FAILURE";


export const GET_FITNESS_DATA_REQUEST = "GET_FITNESS_DATA_REQUEST";
export const GET_FITNESS_DATA_SUCCESS = "GET_FITNESS_DATA_SUCCESS";
export const GET_FITNESS_DATA_FAILURE = "GET_FITNESS_DATA_FAILURE";

export const GET_FURNITURE_DATA_REQUEST = "GET_FURNITURE_DATA_REQUEST";
export const GET_FURNITURE_DATA_SUCCESS = "GET_FURNITURE_DATA_SUCCESS";
export const GET_FURNITURE_DATA_FAILURE = "GET_FURNITURE_DATA_FAILURE";



export const GET_APPLIANCES_REQUEST="GET_APPLIANCES_REQUEST";
export const GET_APPLIANCES_SUCCESS="GET_APPLIANCES_SUCCESS";
export const GET_APPLIANCES_FAILURE="GET_APPLIANCES_FAILURE";

