export const GET_ELECTRONICS_DATA_REQUEST = "GET_ELECTRONICS_DATA_REQUEST";
export const GET_ELECTRONICS_DATA_SUCCESS = "GET_ELECTRONICS_DATA_SUCCESS";
export const GET_ELECTRONICS_DATA_FAILURE = "GET_ELECTRONICS_DATA_FAILURE";
